routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('admin.home.dashboard');
})->name('home');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function(){
    Route::get('/', [\App\Http\Controllers\RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:role_view','auth');

    Route::get('/create', [\App\Http\Controllers\RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:role_create','auth');

    Route::post('/store', [\App\Http\Controllers\RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:role_store','auth');

    Route::get('/{id}', [\App\Http\Controllers\RoleController::class, 'show'])
        ->name('show')
        ->middleware('permission:role_show','auth');

    Route::get('/edit/{id}', [\App\Http\Controllers\RoleController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:role_edit','auth');

    Route::put('/update/{id}', [\App\Http\Controllers\RoleController::class, 'update'])
        ->name('update')
        ->middleware('permission:role_update','auth');

    Route::delete('/delete/{id}', [\App\Http\Controllers\RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:role_delete','auth');
});



//-----------------------------User----------------------------------
Route::get('users/create', [\App\Http\Controllers\UserController::class, 'create'])
    ->name('users.create')
    ->middleware('permission:user_create','auth');

Route::get('users/{id}', [\App\Http\Controllers\UserController::class, 'show'])
    ->name('users.show')
    ->middleware('permission:user_show','auth');

Route::delete('users/delete/{id}', [\App\Http\Controllers\UserController::class, 'destroy'])
    ->name('users.destroy')
    ->middleware('permission:user_delete','auth');

Route::get('users/edit/{id}', [\App\Http\Controllers\UserController::class, 'edit'])
    ->name('users.edit')
    ->middleware('permission:user_edit','auth');

Route::post('users/store', [\App\Http\Controllers\UserController::class, 'store'])
    ->name('users.store')
    ->middleware('permission:user_store','auth');

Route::put('users/update/{id}',[\App\Http\Controllers\UserController::class,'update'])
    ->name('users.update')
    ->middleware('permission:user_update','auth');

Route::get('/user', [\App\Http\Controllers\UserController::class, 'index'])
    ->name('users.index')
    ->middleware('permission:user_view','auth');


// -------------------Category ----------------------------\\

Route::get('categories',[\App\Http\Controllers\CategoryController::class,'index'])
    ->name('categories.index')
    ->middleware('permission:category_view','auth');

Route::get('categorie/create',[\App\Http\Controllers\CategoryController::class,'create'])
    ->name('categories.create')
    ->middleware('permission:category_create','auth');

Route::post('categories/store',[\App\Http\Controllers\CategoryController::class,'store'])
    ->name('categories.store')
    ->middleware('permission:category_store','auth');

Route::get('categories/edit/{id}',[\App\Http\Controllers\CategoryController::class,'edit'])
    ->name('categories.edit')
    ->middleware('permission:category_edit','auth');

Route::put('categories/update/{id}',[\App\Http\Controllers\CategoryController::class,'update'])
    ->name('categories.update')
    ->middleware('permission:category_update','auth');

Route::delete('categories/delete/{id}',[\App\Http\Controllers\CategoryController::class,'destroy'])
    ->name('categories.destroy')
    ->middleware('permission:category_delete','auth');;

Route::get('categorie/list',[\App\Http\Controllers\CategoryController::class,'list'])
    ->name('categories.list')
    ->middleware('permission:category_view','auth');;

// -------------------Product ----------------------------\\

Route::get('products',[\App\Http\Controllers\ProductController::class,'index'])
    ->name('products.index');

Route::get('prodcuts/{id}',[\App\Http\Controllers\ProductController::class,'show'])
    ->name('products.show');

Route::get('products/create',[\App\Http\Controllers\ProductController::class,'create'])
    ->name('products.create');

Route::get('prodcuts/edit/{id}',[\App\Http\Controllers\ProductController::class,'edit'])
    ->name('products.edit');

Route::post('products/store',[\App\Http\Controllers\ProductController::class,'store'])
    ->name('products.store');

Route::put('prodcuts/update/{id}',[\App\Http\Controllers\ProductController::class,'update'])
    ->name('products.update');

Route::delete('products/delete/{id}',[\App\Http\Controllers\ProductController::class,'destroy'])
    ->name('products.destroy');

Route::get('products/list',[\App\Http\Controllers\ProductController::class,'list'])
    ->name('products.list');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';
    protected $fillable = [
        'name',
        'display_name'
    ];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function attachPermission($permissionID)
    {
        return $this->permissions()->attach($permissionID);
    }

    public function permissions()
    {
        return $this->belongsToMany(
            Permission::class,
            'role_permission',
            'role_id',
            'permission_id'
        );
    }

    public function roleUsers()
    {
        return $this->belongsToMany(
            User::class,
            'role_user',
            'role_id',
            'user_id'
        );
    }

    public function detachUser()
    {
        return $this->roleUsers()->detach();
    }

    public function detachPermission()
    {
        return $this->permissions()->detach();
    }

    public function syncPermission($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }

    public function hasPermission($permission)
    {
        return $this->permissions->contains('name', $permission);
    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleRequest;
use App\Repositories\PermissionRepository;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class RoleController extends Controller
{
    protected $roleService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
    }

    public function index(Request $request)
    {
        $roles = $this->roleService->search($request);
        return view('admin.roles.index', compact('roles'));
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(RoleRequest $request)
    {
        $this->roleService->create($request);

        return redirect(route('roles.index'))->with('message', 'Roles created successfully');
    }

    public function show($id)
    {
        $role = $this->roleService->find($id);
        return view('admin.roles.show', compact('role'));
    }

    public function edit($id)
    {
        $role = $this->roleService->find($id);
        return view('admin.roles.edit', compact('role'));
    }

    public function update(RoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);

        return redirect(route('roles.index'))->with('message', 'Roles updated successfully');
    }

    public function destroy($id)
    {
        $this->roleService->delete($id);

        return redirect(route('roles.index'))->with('message', 'Roles deleted successfully');
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')

{{--@section('title', 'Dashboard')--}}

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Roles</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Add Role</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form action="{{ route('roles.store') }}" method="POST">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Name</label>
                                        <input type="text" class="form-control" name="name" placeholder="Name . . .">
                                        <p>
                                        @error('name')
                                        <div class="link-danger">{{ $message }}</div>
                                        @enderror
                                        </p>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Display Name</label>
                                        <input type="text" class="form-control" name="display_name"
                                               placeholder="Display name . . .">
                                    </div>
                                    <p>
                                    @error('display_name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                    </p>
                                    <div class="form-check">
                                        <input class="form-check-input select-all-permission" type="checkbox"
                                               id="checkAll">
                                        <label class="form-label">Permission</label>
                                        <div class="row">
                                            @foreach($permissionGroup as $group => $permission)
                                                <div class="col car">
                                                    <input class="checkbox_wrapper" type="checkbox" id="checkAlla">
                                                    <label class="form-label"><b>{{ucfirst( $group )}}</b></label>
                                                    @foreach($permission as $key => $permissionItem)
                                                        <div class="card-text">
                                                            <div class="form-check">
                                                                <input class="b" type="checkbox" id="checkAllb"
                                                                       name="permission_name[]"
                                                                       value="{{ $permissionItem->id }}">
                                                                <label class="form-check-label"
                                                                       for="flexCheckDefault">
                                                                    {{ $permissionItem->display_name }}
                                                                </label>
                                                            </div>
                                                        </div>
                                                    @endforeach
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <!-- Four equal columns -->
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!--/.col (left) -->
                    <!-- right column -->
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Roles</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('roles.index')}}">Roles</a></li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Update Role</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form action="{{route('roles.update', $role->id)}}" method="POST">
                                @method('PUT')
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Name</label>
                                        <input type="text" class="form-control" name="name" value="{{$role->name}}">
                                        <p>
                                        @error('name')
                                        <div class="link-danger">{{ $message }}</div>
                                        @enderror
                                        </p>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Display Name</label>
                                        <input type="text" class="form-control" name="display_name"
                                               value="{{$role->display_name}}">
                                        <p>
                                        @error('display_name')
                                        <div class="link-danger">{{ $message }}</div>
                                        @enderror
                                        </p>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input select-all-permission" type="checkbox"
                                               id="checkAll">
                                        <label class="form-label">Permission</label>
                                        <div class="row">
                                            @foreach($permissionGroup as $group => $permission)
                                                <div class="col car">
                                                    @foreach($permission as $key => $permissionItem)
                                                        <div class="card-text">
                                                            <div class="form-check">
                                                                <input
                                                                    {@foreach($role->permissions as $item)
                                                                    {{ $item->id == $permissionItem->id ? 'checked' : '' }}
                                                                    @endforeach
                                                                    class="b"
                                                                    type="checkbox" id="checkAllb"
                                                                    name="permission_name[]"
                                                                    value="{{ $permissionItem->id }}">
                                                                <label class="form-check-label"
                                                                       for="flexCheckDefault">
                                                                    {{ $permissionItem->display_name }}
                                                                </label>
                                                            </div>
                                                        </div>
                                                    @endforeach
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!--/.col (left) -->
                    <!-- right column -->
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')
@php
$stt = (($_GET['page'] ?? 1) - 1) * 5;
@endphp
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Roles</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Roles</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card-header clearfix">
                            <a href="{{route('roles.create')}}" type="button" class="btn btn-primary float-left"><i
                                    class="fas fa-plus"></i> Add Role</a>
                        </div>
                        <!-- /.card -->
                        @if ($message = Session::get('message'))
                            <div class="alert alert-success">
                                <p class="text-white">{{ $message }}</p>
                            </div>
                        @endif
                            <!-- /.card-header -->
                        <div class="card-header" style="padding-left: 20%; background: #f3f8fa ">
                            <div class="col-md-10" style="margin-top: 5px; margin-bottom: 10px">
                                <form method="GET" class="m-md-3 d-flex" style="padding-right: 20%">
                                    <input type="search" name="name" value="{{ request('name') }}"
                                           class="form-control"
                                           placeholder="search ...">
                                    <button type="submit" class="btn btn-primary" style="margin-left: 7px">
                                        search
                                    </button>
                                </form>
                            </div>
                        </div>
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th style="width: 5%">ID</th>
                                        <th style="width: 10%">Name</th>
                                        <th>Permission</th>
                                        <th style="width: 15%">Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $role)
                                        <tr>
                                            <td>{{++$stt}}</td>
                                            <td>{{$role->display_name}}</td>
                                            <td >
                                                <div>@foreach($role->permissions as $key=>$permission)
                                                    <span style="font-size: 14px" class="text-black">{{ $permission->display_name }}
                                                        {{ $key + 1 == $role->permissions->count() ? '.' : ',' }}
                                                    </span>
                                                @endforeach
                                                </div></td>
                                            <td>
                                                    @hasPermission('role_show')
                                                    <a href="{{route('roles.show', $role->id)}}"
                                                       class="badge bg-success"><i class="far fa-eye"></i></a>
                                                    @endhasPermission
                                                    @hasPermission('role_edit')
                                                    <a href="{{route('roles.edit', $role->id)}}"
                                                       class="badge bg-yellow"><i class="fas fa-edit"></i></a>
                                                    @endhasPermission
                                                    @hasPermission('role_delete')
                                                    <a  title="Delete" >
                                                        <button  data-id="{{$role->id}}"
                                                            type="submit" class="badge bg-danger dele-role-btn" onclick="">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                        <form id="delete-role-form-{{$role->id}}"
                                                            action="{{route('roles.destroy', $role->id)}}" method="POST">
                                                            @method('DELETE')
                                                            @csrf
                                                        </form>
                                                    </a>
                                                    @endhasPermission
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                <p>
                                    {{$roles->appends(request()->all())->Links()}}
                                </p>

                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/roles/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Show Roles</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active"><a href="{{route('roles.index')}}">Roles</a></li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- ./col -->
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <dl class="row">
                                    <dt class="col-sm-2">ID</dt>
                                    <dd class="col-sm-10">{{$role->id}}</dd>
                                    <dt class="col-sm-2">Name</dt>
                                    <dd class="col-sm-10">{{$role->name}}</dd>
                                    <dt class="col-sm-2">Display_Name</dt>
                                    <dd class="col-sm-10">{{$role->display_name}}</dd>
                                    <dt class="col-sm-2">Permission</dt>
                                    <dd class="col-sm-10">
                                        @foreach($role->permissions as $permission)
                                            <span style="font-size: 12px; background-color:#007bff"
                                                  class="badge badge-warning">{{ $permission->display_name }}</span>
                                        @endforeach
                                    </dd>
                                </dl>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- ./col -->
                </div>
                <!-- /.container-fluid -->
            </div>
        </section>
        <!-- /.content -->
    </div>
@endsection