routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('admin.home.dashboard');
})->name('home');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function(){
    Route::get('/', [\App\Http\Controllers\RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:role_view','auth');

    Route::get('/create', [\App\Http\Controllers\RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:role_create','auth');

    Route::post('/store', [\App\Http\Controllers\RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:role_store','auth');

    Route::get('/{id}', [\App\Http\Controllers\RoleController::class, 'show'])
        ->name('show')
        ->middleware('permission:role_show','auth');

    Route::get('/edit/{id}', [\App\Http\Controllers\RoleController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:role_edit','auth');

    Route::put('/update/{id}', [\App\Http\Controllers\RoleController::class, 'update'])
        ->name('update')
        ->middleware('permission:role_update','auth');

    Route::delete('/delete/{id}', [\App\Http\Controllers\RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:role_delete','auth');
});



//-----------------------------User----------------------------------
Route::get('users/create', [\App\Http\Controllers\UserController::class, 'create'])
    ->name('users.create')
    ->middleware('permission:user_create','auth');

Route::get('users/{id}', [\App\Http\Controllers\UserController::class, 'show'])
    ->name('users.show')
    ->middleware('permission:user_show','auth');

Route::delete('users/delete/{id}', [\App\Http\Controllers\UserController::class, 'destroy'])
    ->name('users.destroy')
    ->middleware('permission:user_delete','auth');

Route::get('users/edit/{id}', [\App\Http\Controllers\UserController::class, 'edit'])
    ->name('users.edit')
    ->middleware('permission:user_edit','auth');

Route::post('users/store', [\App\Http\Controllers\UserController::class, 'store'])
    ->name('users.store')
    ->middleware('permission:user_store','auth');

Route::put('users/update/{id}',[\App\Http\Controllers\UserController::class,'update'])
    ->name('users.update')
    ->middleware('permission:user_update','auth');

Route::get('/user', [\App\Http\Controllers\UserController::class, 'index'])
    ->name('users.index')
    ->middleware('permission:user_view','auth');


// -------------------Category ----------------------------\\

Route::get('categories',[\App\Http\Controllers\CategoryController::class,'index'])
    ->name('categories.index')
    ->middleware('permission:category_view','auth');

Route::get('categorie/create',[\App\Http\Controllers\CategoryController::class,'create'])
    ->name('categories.create')
    ->middleware('permission:category_create','auth');

Route::post('categories/store',[\App\Http\Controllers\CategoryController::class,'store'])
    ->name('categories.store')
    ->middleware('permission:category_store','auth');

Route::get('categories/edit/{id}',[\App\Http\Controllers\CategoryController::class,'edit'])
    ->name('categories.edit')
    ->middleware('permission:category_edit','auth');

Route::put('categories/update/{id}',[\App\Http\Controllers\CategoryController::class,'update'])
    ->name('categories.update')
    ->middleware('permission:category_update','auth');

Route::delete('categories/delete/{id}',[\App\Http\Controllers\CategoryController::class,'destroy'])
    ->name('categories.destroy')
    ->middleware('permission:category_delete','auth');;

Route::get('categorie/list',[\App\Http\Controllers\CategoryController::class,'list'])
    ->name('categories.list')
    ->middleware('permission:category_view','auth');;

// -------------------Product ----------------------------\\

Route::get('products',[\App\Http\Controllers\ProductController::class,'index'])
    ->name('products.index');

Route::get('prodcuts/{id}',[\App\Http\Controllers\ProductController::class,'show'])
    ->name('products.show');

Route::get('products/create',[\App\Http\Controllers\ProductController::class,'create'])
    ->name('products.create');

Route::get('prodcuts/edit/{id}',[\App\Http\Controllers\ProductController::class,'edit'])
    ->name('products.edit');

Route::post('products/store',[\App\Http\Controllers\ProductController::class,'store'])
    ->name('products.store');

Route::put('prodcuts/update/{id}',[\App\Http\Controllers\ProductController::class,'update'])
    ->name('products.update');

Route::delete('products/delete/{id}',[\App\Http\Controllers\ProductController::class,'destroy'])
    ->name('products.destroy');

Route::get('products/list',[\App\Http\Controllers\ProductController::class,'list'])
    ->name('products.list');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Navbar -->
@include('admin.layouts.nav')
<!-- /.navbar -->

    <!-- Main Sidebar Container -->
@include('admin.layouts.siderb')

<!-- Content Wrapper. Contains page content -->
@yield('content')
<!-- /.content-wrapper -->
@include('admin.layouts.footer')

<!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@include('admin.layouts.js')
@stack('scripts')
@stack('js')
</body>
</html>

resources/views/admin/layouts/app1.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.layouts.head')

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Navbar -->
@include('admin.layouts.nav')
<!-- /.navbar -->

    <!-- Main Sidebar Container -->
@include('admin.layouts.siderb')

<!-- Content Wrapper. Contains page content -->
@yield('content')
<!-- /.content-wrapper -->
@include('admin.layouts.footer')

<!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@include('admin.layouts.js')
@stack('scripts')
@stack('js')
</body>
</html>
<?php

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Nguyễn Tuấn Anh <a href="https://www.facebook.com/profile.php?id=100007812761473">tuananh.com</a>.</strong>
    <div class="float-right d-none d-sm-inline-block">

    </div>
</footer>

resources/views/admin/layouts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>2510_Store</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{asset('plugins/jqvmap/jqvmap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('plugins/daterangepicker/daterangepicker.css')}}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.min.css')}}">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Latest compiled JavaScript -->

{{--    <script src="/js/base.js"></script>--}}
{{--    <script src="{{asset('js/category.js')}}"></script>--}}
{{--    <script src="{{asset('js/product.js')}}"></script>--}}
</head>

resources/views/admin/layouts/js.blade.php
<!-- jQuery -->
<script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{asset('plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('dist/js/adminlte.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('dist/js/demo.js')}}"></script>
<!-- jQuery -->
<script src="{{asset('js/base.js')}}"></script>
<script src="{{asset('js/role.js')}}"></script>
<script src="{{asset('js/category.js')}}"></script>
{{--<script src="{{asset('js/product.js')}}"></script>--}}
<script src="{{asset('js/loadImage.js')}}"></script>
<script src="{{asset('js/user.js')}}"></script>
<script src="{{asset('js/arletMessage.js')}}"></script>
<!-- sweetalert2 -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" type="text/javascript" charset="utf-8" async defer></script>
<script src="{{asset('dist/js/pages/dashboard.js')}}"></script>
{{--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>--}}
<script>
    $(document).ready(function () {
        $("#checkAll").change(function () {
            $("input:checkbox").prop('checked', $(this).prop("checked"));
        });
        $('.b').on('click', function () {
            if ($('.b:checked').length == $('.b').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });

    });
</script>

resources/views/admin/layouts/nav.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        @guest
            @if (Route::has('login'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
            @endif

            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link " href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }}
                </a>
            </li>
            <li class="nav-item">
                <div style="margin-top: 4px" class="" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" style="padding-left: 0px ; padding-right: 0px;color: rgba(0,0,0,.55);" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div></li>
        @endguest
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

resources/views/admin/layouts/siderb.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
  <a href="{{--  {{route('home')}}--}}" class="brand-link">
        <img src=" {{asset('dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">2510 Store</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="{{route('home')}}" class="nav-link {{Route::is('home') || Route::is('home')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-header">INTERFACE</li>
                <li class="nav-item">
                    <a  href="{{route('users.index')}}" class="nav-link {{Route::is('users.*') || Route::is('user.*')  ? 'active' : '' }}">
                        <i class="fas fa-users"></i>
                        <p>&ensp;Users</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('roles.index')}}" class="nav-link {{Route::is('roles.*') || Route::is('roles.*')  ? 'active' : '' }}">
                        <i class="fas fa-gavel"></i>
                        <p>&ensp; Roles</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('categories.index')}}" class="nav-link {{Route::is('categories.*') || Route::is('categories.*')  ? 'active' : '' }}">
                        <i class="fas fa-bezier-curve"></i>
                        <p> &nbsp; Categories</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('products.index')}}" class="nav-link {{Route::is('prodcuts.*') || Route::is('products.*')  ? 'active' : '' }}">
                        <i class="fas fa-clone"></i>
                        <p>&nbsp;&nbsp;&nbsp;Product</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>